language: generic

services:
  - docker

before_install:
  - echo "cloning universe"
  - git clone --single-branch -b master https://github.com/nkalband/hello_world2.git

import: ./hello_world2/common.yml