language: generic

services:
  - docker

before_install:
  - echo "cloning hello_world2"
  - git clone --single-branch -b master https://github.com/nkalband/hello_world2.git
  - ls -ltrR
  
import: 
  - source : hello_world2/common.yml
# import: nkalband/hello_world2:common.yml
