version: 2.1
orbs:
    hello: circleci/hello-build@0.0.5
    win: circleci/windows@2.3.0
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: echo 'Hello, Windows' && uname -a && uname -p
  hello:
    machine:
      image: ubuntu-2004:202010-01 # recommended linux image
    steps:
        - run: echo 'Hi hello/hello-build' && uname -a && uname -p
workflows:
    "Hello Workflow":
        jobs:
            - hello
            - build



